name: Daily Random Auto Commit

on:
  schedule:
    - cron: '17 10 * * 1-4,6'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "hamza bari"
          git config --global user.email "barihamza73@gmail.com"

      - name: Generate Random Commits
        run: |
          MIN_COMMITS=3
          MAX_COMMITS=17

          NUM_COMMITS=$((RANDOM % (MAX_COMMITS - MIN_COMMITS + 1) + MIN_COMMITS))

          echo "Creating $NUM_COMMITS commits"

          if [ ! -f messages.txt ]; then
            echo "messages.txt not found!"
            exit 1
          fi
          
          shuf messages.txt | head -n $NUM_COMMITS > selected_messages.txt

          while IFS= read -r COMMIT_MESSAGE
          do
            echo "$(date '+%Y-%m-%d %H:%M:%S') - $COMMIT_MESSAGE" >> commits-log.md

            git add commits-log.md
            git commit -m "$COMMIT_MESSAGE"
          done < selected_messages.txt

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_COMMIT_KEY }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          git pull --rebase origin main
          git push origin main